//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.01.24 at 11:05:17 PM CET 
//


package org.edgo.jtg.core.config;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="GeneratedPackage" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="GeneratorOutputDir" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="JarOutputDir" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ProjectFile" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Schema" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SchemaDir" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SchemaPackage" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SourceOutputDir" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="StartTemplate" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TemplateDir" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="UsingCache" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="true"/>
 *             &lt;enumeration value="false"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "jtgConfiguration")
public class JtgConfiguration {

    @XmlAttribute(name = "GeneratedPackage", required = true)
    protected String generatedPackage;
    @XmlAttribute(name = "GeneratorOutputDir", required = true)
    protected String generatorOutputDir;
    @XmlAttribute(name = "JarOutputDir", required = true)
    protected String jarOutputDir;
    @XmlAttribute(name = "ProjectFile", required = true)
    protected String projectFile;
    @XmlAttribute(name = "Schema", required = true)
    protected String schema;
    @XmlAttribute(name = "SchemaDir", required = true)
    protected String schemaDir;
    @XmlAttribute(name = "SchemaPackage", required = true)
    protected String schemaPackage;
    @XmlAttribute(name = "SourceOutputDir", required = true)
    protected String sourceOutputDir;
    @XmlAttribute(name = "StartTemplate", required = true)
    protected String startTemplate;
    @XmlAttribute(name = "TemplateDir", required = true)
    protected String templateDir;
    @XmlAttribute(name = "UsingCache", required = true)
    protected String usingCache;
    @XmlAttribute(name = "Command", required = false)
    protected String command;

    /**
     * Gets the value of the generatedPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneratedPackage() {
        return generatedPackage;
    }

    /**
     * Sets the value of the generatedPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneratedPackage(String value) {
        this.generatedPackage = value;
    }

    /**
     * Gets the value of the generatorOutputDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGeneratorOutputDir() {
        return generatorOutputDir;
    }

    /**
     * Sets the value of the generatorOutputDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGeneratorOutputDir(String value) {
        this.generatorOutputDir = value;
    }

    /**
     * Gets the value of the jarOutputDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJarOutputDir() {
        return jarOutputDir;
    }

    /**
     * Sets the value of the jarOutputDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJarOutputDir(String value) {
        this.jarOutputDir = value;
    }

    /**
     * Gets the value of the projectFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectFile() {
        return projectFile;
    }

    /**
     * Sets the value of the projectFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectFile(String value) {
        this.projectFile = value;
    }

    /**
     * Gets the value of the schema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchema() {
        return schema;
    }

    /**
     * Sets the value of the schema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchema(String value) {
        this.schema = value;
    }

    /**
     * Gets the value of the schemaDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaDir() {
        return schemaDir;
    }

    /**
     * Sets the value of the schemaDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaDir(String value) {
        this.schemaDir = value;
    }

    /**
     * Gets the value of the schemaPackage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaPackage() {
        return schemaPackage;
    }

    /**
     * Sets the value of the schemaPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaPackage(String value) {
        this.schemaPackage = value;
    }

    /**
     * Gets the value of the sourceOutputDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceOutputDir() {
        return sourceOutputDir;
    }

    /**
     * Sets the value of the sourceOutputDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceOutputDir(String value) {
        this.sourceOutputDir = value;
    }

    /**
     * Gets the value of the startTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStartTemplate() {
        return startTemplate;
    }

    /**
     * Sets the value of the startTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStartTemplate(String value) {
        this.startTemplate = value;
    }

    /**
     * Gets the value of the templateDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplateDir() {
        return templateDir;
    }

    /**
     * Sets the value of the templateDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplateDir(String value) {
        this.templateDir = value;
    }

    /**
     * Gets the value of the usingCache property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsingCache() {
        return usingCache;
    }

    /**
     * Sets the value of the usingCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsingCache(String value) {
        this.usingCache = value;
    }

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
	public String getCommand() {
		return command;
	}

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
	public void setCommand(String command) {
		this.command = command;
	}

}
